global:
  scrape_interval: 10s # Raspa as métricas a cada 15 segundos

scrape_configs:
  - job_name: 'gestao_vagas'
    metrics_path: '/actuator/prometheus' # Onde o Spring expõe os dados
    static_configs:
      # host.docker.internal = O endereço da sua máquina visto de dentro do Docker
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "api_gestao_vagas"